<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>NoHidden.Core</AssemblyName>
    <RootNamespace>NoHidden</RootNamespace>
  </PropertyGroup>
</Project>
